const country = [
  {
    id: 1,
    title: 'Argentina',
    category: 'South America',
    time: '-03:00',
    img: './images/item-5.png',
    desc: `Capital : Buenos Aires`,
  },
  {
    id: 2,
    title: 'Australia',
    category: 'Oceania and Australia',
    time: '+11:00',
    img: './images/item-6.png',
    desc: `Capital : Canberra`,
  },
  {
    id: 3,
    title: 'Costa Rica',
    category: 'North America',
    time: '-06:00',
    img: './images/item-10.png',
    desc: `Capital : San José`,
  },
  {
    id: 4,
    title: 'New Zealand',
    category: 'Oceania and Australia',
    time: '+13:00',
    img: './images/item-12.png',
    desc: `Capital : Wellington`,
  },
  {
    id: 5,
    title: 'Algeria',
    category: 'Africa',
    time: '+01:00',
    img: './images/item-1.png',
    desc: `Capital : Algiers`,
  },
  {
    id: 6,
    title: 'Afghanistan',
    category: 'Asia',
    time: '+04:30',
    img: './images/item-2.png',
    desc: `Capital : Kabul`,
  },
  {
    id: 7,
    title: 'Egypt',
    category: 'Africa',
    time: '+02:00',
    img: './images/item-7.png',
    desc: `Capital : Cairo`,
  },
  {
    id: 8,
    title: 'Bangladesh',
    category: 'Asia',
    time: '+06:00',
    img: './images/item-8.png',
    desc: `Capital : Dhaka`,
  },
  {
    id: 9,
    title: 'Belgium',
    category: 'Europe',
    time: '+02:00',
    img: './images/item-9.png',
    desc: `Capital : 	Brussels`,
  },
  {
    id: 10,
    title: 'Austria',
    category: 'Europe',
    time: '+02:00',
    img: './images/item-3.png',
    desc: `Capital : Vienna`,
  },
  {
    id: 11,
    title: 'Brazil',
    category: 'South America',
    time: '-03:00',
    img: './images/item-11.png',
    desc: `Capital : Brasília`,
  },
  {
    id: 12,
    title: 'Canada',
    category: 'North America',
    time: '-05:00',
    img: './images/item-4.png',
    desc: `Capital : Ottawa`,
  },
];
export default country;
